### ISSUE TITLE
move fn_functions from protocol to application

### ISSUE THREAD

**Issue by p-h-a-i-l** [bipropellant/hbprotocol#15]
move fn_ functions to separate file out of hbprotocol.
remove many buffer variables and use one generic receive buffer.

(from https://github.com/bipropellant/hbprotocol/pull/13)

**Comment by btsimonh** [comment]
i think we shold move protocol.c + ascii_protocol + associated to main app.  This one should just be the mechanics of the machine protocol?  thoughts?

**Comment by p-h-a-i-l** [comment]
I like how params is in sync in all my repos. I will do a proposal how to reduce global variables across submodules. The general Idea is in my head, but I need some time :)

**Comment by btsimonh** [comment]
ok, 'cause i just had to mod both repos again.....

**Comment by p-h-a-i-l** [comment]
fixed in https://github.com/bipropellant/bipropellant-protocol/pull/26
