### ISSUE TITLE
TxBuffer filling up quickly

### ISSUE THREAD

**Issue by p-h-a-i-l** [bipropellant/hbprotocol#2]
Tonight I tested the modifications I did on the code, got it running faster than expected :)
One thing I noticed: The TXbuffer on the control side is filling up quickly: for each PwmSteerCmd message I send, the buffer grew 8 bytes.
Did you notice something similar? I didn't have a look at the hoverboard buffer yet. For now control is quite laggy and as soon as I add HallData, almost unusable.

**Comment by btsimonh** [comment]
hmm...  8 bytes is the size of your message 
1+1+1+1+4+1 = 8? 
(SOM+CI+LEN+CMD+(sizeof PWM_STEER_CMD)+CS)
ack should be 
1+1+1+1+1 = 5?
(SOM+CI+LEN+ACK+CS)
and return message should be
1+1+1+1+1+1 = 6? 
(SOM+CI+LEN+CMD+RESULT+CS)


double check your structure alignment on the ESP side - and maybe move the pack(push,1) and pack(pop) to the top and bottom of protocol.h on both ends.

Seems you ware not getting the ack, and not timing out the message sending to remove it from the buffer?
Does the command seem received on the HB side?

**Comment by p-h-a-i-l** [comment]
We need a wireshark plugin for our protocol for sure ;)

Maybe a quick python script first to  generate and read messages and responses.

**Comment by btsimonh** [comment]
are you TCP or UDP to the ESP?  And passing the stuff raw?
For PC -> HB. do you run the ESP transparent (i.e. deal with acks at PC), or trust the IP and have the ESP deal with the 'unreliable' serial?
Never scripted for wireshark, but used it plenty.  Must be a script we can adapt very easily...

**Comment by p-h-a-i-l** [comment]
Right now the ESP handles the serial on its own. ESP to ESP was via ESPnow, but I just ran out of time and needed to hack something together. Looking for a better ways right now,


> Does the command seem received on the HB side?

Yes, running motors. just with lots of delay.

**Comment by btsimonh** [comment]
Q: Are you sure that the PROTOCOL_STAT structure starts all zeroed?
Just comparing repos (the firmware does not accept my serial...), and note that protocol_init() is unused, so no memset of the whole lot to zero any more...

**Comment by p-h-a-i-l** [comment]
protocol_init was not necessary anymore. Init is done here:
https://github.com/bipropellant/hbprotocol/blob/379392de0e2a3f1a448f35a6c7f9c0e7342dcef1/protocol.c#L155-L195

also see https://en.cppreference.com/w/c/language/struct_initialization

> All members that are not initialized explicitly are initialized implicitly the same way as objects that have static storage duration.


Make sure to pull hbprotocol! Did some bugfixes yesterday evening, but in the hoverboard-protocol repo the lastest commit is not referenced yet.

**Comment by btsimonh** [comment]
ok, so they SHOULD be zeroed.
I got no data because I'd not done 'unlockASCII'!!!!
you got me again!.
doing some light tests - just got ? to work after above.... will revert all (my) changes related to PROTOCOL_STAT and try again...

**Comment by p-h-a-i-l** [comment]
> I got no data because I'd not done 'unlockASCII'!!!!
> you got me again!.

Do you have a proposal where best do document this feature? I didn't like the idea that random characters without any checksum can lead to actions

**Comment by btsimonh** [comment]
we need to add a wiki page for the ascii protocol anyway :).
I'd suggest we add a note to BOTH readmes referring to the wiki for explanation.... I'll add an unstarted task to the project.

**Comment by btsimonh** [comment]
Playing yesterday, serial was working nicely for me in terms of responsiveness....

**Comment by p-h-a-i-l** [comment]
Found the problem:
We still acknowledge packages with the same package minus data. This leads to some very unfortunate loops..

**Comment by btsimonh** [comment]
yes, at the high level, a command may be responded to with the same command with different parameters....  e.g. WRITEVAL|code|DATA sent to HB returns WRITEVAL|code|1 to confirm write.  I did not make this obvious in wiki; some examples would be good if you happen to have current captures!

**Comment by p-h-a-i-l** [comment]
My proposal would be to just reply with an ACK, I don't yet understand the use case for more complex replies.

I could also check if the payload is zero. But that wouldn't work in the scenario you described.
