### ISSUE TITLE
arduino compile error

### ISSUE THREAD

**Issue by chronicle972** [bipropellant/hbprotocol#29]
Have this error when I try to compile the api on the arduino:
 stm32f1xx_hal.h: No such file or directory

**Comment by p-h-a-i-l** [comment]
The library shouldn't have this dependency anymore. Can you tell me from where you get the source code?

**Comment by chronicle972** [comment]
I took it in the API

**Comment by p-h-a-i-l** [comment]
did you clone it with git, or did you download a .zip, or did you use the Arduino library manager?

**Comment by chronicle972** [comment]
i used the .zip

**Comment by p-h-a-i-l** [comment]
From where?

**Comment by chronicle972** [comment]
from here: https://github.com/bipropellant/bipropellant-hoverboard-api

**Comment by verial** [comment]
library this questioning https://www.arduinolibraries.info/libraries/hoverboard-api ?

**Comment by verial** [comment]
библиотеку эту стоит https://www.arduinolibraries.info/libraries/hoverboard-api ?

**Comment by btsimonh** [comment]
ooo..  getting a bit official - library in a library management system!

**Comment by verial** [comment]
I only work for her.
