### ISSUE TITLE
vesc protocol

### ISSUE THREAD

**Issue by p-h-a-i-l** [bipropellant/hbprotocol#3]
Do you guys know vedder esc (http://vedder.se/)? I should also have some means of communicating over UART. Had a quick look, but couldn't find the relevant code..

**Comment by btsimonh** [comment]
that is very interesting.
We should add a project item to examine the VESC code, and see what we can use; his protocol approach is very similar to ours - and maybe the BLDC code is better.  It's still unlikely to have the very slow control that I crave...  but a comparison would be interesting.
s

**Comment by AntumArk** [comment]
Hello,
His protocol is really well made, but it may take up too much space. My team had experimented with it, and were able to run bicycle motor fairly slowly and efficiently ( 50 RPM - 60% eff). Compared to regular commutation, it is 10-20 % efficiency increase. 
I am kind of struggling to find how to use your protocol. I am thinking about using it with c# application.
