### ISSUE TITLE
Status of COBS/R pull request

### ISSUE THREAD

**Issue by adverst** [bipropellant/hbprotocol#34]
Hi @p-h-a-i-l  - just wondering on teh status of the open COBS/R pull request? 

My own project has been on hold for months, I'm finally getting back to it. I have my HB running with an older version of the firmware, everything sort of works. I have a bluetooth wii remote controlling the hoverboard via a raspberry pi. Currently it's only using the ASCII protocol though. I was planning to switch to the machine protocol as I'd like a bit finer control (and to retrieve information more easily about speed etc). I saw this PR sitting there with all the protocol changes though, so don't want to implement the 'old' protocol if it's going to be replaced.

I can wing it and build off the COBS/R branch but figured if this PR is likely to be merged and used by the main firmware I could wait

**Comment by p-h-a-i-l** [comment]
merging right now :)
